"""
Output Generator Module
Creates downloadable Markdown and PDF files from analysis results.
"""

import os
from datetime import datetime
import markdown2
from weasyprint import HTML
from typing import Dict
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def generate_markdown(analysis: Dict[str, any], metadata: Dict[str, str]) -> str:
    """
    Create formatted Markdown content.

    Args:
        analysis: Parsed Claude response
        metadata: {title, presenters, date, time, github_url (optional)}

    Returns:
        Formatted Markdown string
    """
    title = metadata.get('title', 'Untitled Presentation')
    presenters = metadata.get('presenters', 'Unknown')
    date = metadata.get('date', datetime.now().strftime('%B %d, %Y'))
    time = metadata.get('time', datetime.now().strftime('%I:%M %p'))
    github_url = metadata.get('github_url', '')

    # Build GitHub section if URL provided
    github_line = f"**GitHub Repository:** [{github_url}]({github_url})  \n" if github_url else ""

    # Start building markdown
    markdown_content = f"""# Presentation Analysis: {title}

**Presenters:** {presenters}
**Analyzed:** {date} at {time}
{github_line}**Analyzed by:** Presentation Intelligence Tool

---

{analysis.get('raw_response', 'No analysis available.')}

---

*Generated by Presentation Intelligence Tool*
*Powered by Claude AI (Anthropic)*
"""

    return markdown_content


def save_markdown_file(content: str, output_dir: str, filename: str) -> str:
    """
    Save Markdown to file.

    Args:
        content: Markdown content
        output_dir: Directory to save file
        filename: Base filename (without extension)

    Returns:
        File path
    """
    try:
        os.makedirs(output_dir, exist_ok=True)
        file_path = os.path.join(output_dir, f"{filename}.md")

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        logger.info(f"Markdown file saved: {file_path}")
        return file_path

    except Exception as e:
        logger.error(f"Error saving Markdown file: {str(e)}")
        raise


def generate_pdf(markdown_content: str, output_dir: str, filename: str) -> str:
    """
    Convert Markdown to PDF using WeasyPrint.

    Args:
        markdown_content: Markdown content to convert
        output_dir: Directory to save file
        filename: Base filename (without extension)

    Returns:
        PDF file path
    """
    try:
        os.makedirs(output_dir, exist_ok=True)

        # Convert markdown to HTML
        html_content = markdown2.markdown(markdown_content, extras=['tables', 'fenced-code-blocks'])

        # Add CSS styling for PDF
        styled_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <style>
                @page {{
                    size: letter;
                    margin: 2cm;
                }}
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                }}
                h1 {{
                    color: #2c3e50;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 10px;
                }}
                h2 {{
                    color: #34495e;
                    margin-top: 30px;
                    border-bottom: 2px solid #ecf0f1;
                    padding-bottom: 8px;
                }}
                h3 {{
                    color: #7f8c8d;
                    margin-top: 20px;
                }}
                ul, ol {{
                    margin-left: 20px;
                }}
                li {{
                    margin-bottom: 8px;
                }}
                hr {{
                    border: none;
                    border-top: 1px solid #bdc3c7;
                    margin: 30px 0;
                }}
                code {{
                    background-color: #f4f4f4;
                    padding: 2px 6px;
                    border-radius: 3px;
                }}
                pre {{
                    background-color: #f4f4f4;
                    padding: 15px;
                    border-radius: 5px;
                    overflow-x: auto;
                }}
                a {{
                    color: #3498db;
                    text-decoration: none;
                }}
                a:hover {{
                    text-decoration: underline;
                }}
            </style>
        </head>
        <body>
            {html_content}
        </body>
        </html>
        """

        # Generate PDF
        pdf_path = os.path.join(output_dir, f"{filename}.pdf")
        HTML(string=styled_html).write_pdf(pdf_path)

        logger.info(f"PDF file saved: {pdf_path}")
        return pdf_path

    except Exception as e:
        logger.error(f"Error generating PDF: {str(e)}")
        raise


def create_outputs(analysis: Dict[str, any], metadata: Dict[str, str],
                   output_dir: str, base_filename: str) -> Dict[str, str]:
    """
    Generate both Markdown and PDF files.

    Args:
        analysis: Claude analysis result
        metadata: Presentation metadata
        output_dir: Directory to save files
        base_filename: Base filename for outputs

    Returns:
        {
            'markdown_path': str,
            'pdf_path': str
        }
    """
    try:
        # Generate markdown content
        markdown_content = generate_markdown(analysis, metadata)

        # Save markdown file
        md_path = save_markdown_file(markdown_content, output_dir, base_filename)

        # Generate PDF file
        pdf_path = generate_pdf(markdown_content, output_dir, base_filename)

        return {
            'markdown_path': md_path,
            'pdf_path': pdf_path,
            'success': True
        }

    except Exception as e:
        logger.error(f"Error creating outputs: {str(e)}")
        return {
            'markdown_path': '',
            'pdf_path': '',
            'success': False,
            'error': str(e)
        }
